### PR TITLE
test: add gtest into test case

### PR DESCRIPTION
**Pull request by j8xixo12**
I added google test(gtest) test case into daily build test script.

### CODE REVIEW

**Review by yungyuc — CHANGES_REQUESTED** [review]
Since we add the gtest to this action, it's no longer just 'pytest'.  I think we should also change the name to reflect the content.

**Comment by j8xixo12** [comment]
> Since we add the gtest to this action, it's no longer just 'pytest'. I think we should also change the name to reflect the content.

Maybe I can combine pytest & gtest into one test case?
Because Makefile have a target  called  [`test`](https://github.com/yungyuc/turgon/blob/89e9e9d38046d5c7100355d6dd47b45e3cb91f81/spacetime/Makefile#L59)
I think it looks more concise.

**Comment by yungyuc** [comment]
> > Since we add the gtest to this action, it's no longer just 'pytest'. I think we should also change the name to reflect the content.
> 
> Maybe I can combine pytest & gtest into one test case?
> Because Makefile have a target called [`test`](https://github.com/yungyuc/turgon/blob/89e9e9d38046d5c7100355d6dd47b45e3cb91f81/spacetime/Makefile#L59)
> I think it looks more concise.

I think the `gtest` and `pytest` should use two distinct steps.  When one of both fails it will be clear in the GitHub Action (folded) log that which one goes wrong.

Since `gtest` doesn't need Python, it also makes sense to place it before `pytest`.  But I don't think we need to be strict about the ordering, as long as they are adjacent to each other.

**Review by yungyuc — APPROVED** [review]

**Comment by yungyuc** [comment]
Thanks a lot!

**Pull request merged**
